name: CI on PRs with SDK for 3.0.2 (i486)

env:
  RELEASE: 3.0.2.8
  ARCH: i486
  # Do not wait up to the default of 10 minutes for network timeouts in a workflow which runs ca. 3 minutes.
  SEGMENT_DOWNLOAD_TIMEOUT_MINS: 1

on:
  pull_request:
    branches:
      - devel
      - master
  # Allows to run this workflow manually from the Actions tab.
  workflow_dispatch:

defaults:
  run:
    # Note that 'bash' provides -o pipefail, in contrast to the default (i.e., unspecified, which also uses bash) or 'sh',
    # see https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsshell
    shell: sh

# Do not use concurrency in order to enforce checking every commit of a Pull Request.
# See, e.g.: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-only-cancel-in-progress-jobs-or-runs-for-the-current-workflow
#concurrency:
  #group: ci-${{ github.ref_name }}
  # 'false' (default) allows for two concurrent runs, one executing and one freshly enqueued; 'true' for only one; no 'concurrency:' defined for multiple.
  #cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:

    - name: Checkout
      uses: actions/checkout@v3

    # Caching Docker images is not ready yet, see 
    # https://github.com/storeman-developers/harbour-storeman-installer/blob/devel/cache-docker-images_github-ci.md
    #- name: Cache Docker images of the Sailfish-SDK
    #  id: cache-sdk
    #  uses: actions/cache@v3
    #  with:
    #    path: $GITHUB_WORKSPACE/…
    #    key: cache

    - name: Prepare
      run: mkdir RPMS

    - name: Build ${{ env.ARCH }}
      uses: coderus/github-sfos-build@old-stable
      with:
        # Solely builds for i486 on 2.2.0, because of https://github.com/sailfishos-patches/patchmanager/pull/437#issuecomment-1615317003
        release: ${{ env.RELEASE }}
        arch: ${{ env.ARCH }}

    - name: Upload build result
      uses: actions/upload-artifact@v3
      with:
        name: RPM-build-results_${{ github.base_ref }}-${{ env.ARCH }}-SFOS2.2.0+
        path: RPMS/

